event:
  address: Via Vincenzo Gioberti, 39, 56124 Pisa PI
  dates: November 21-22, 2024
  description: "The European Mobility Symposium has the goal of sharing insights from\
    \ recent works on human mobility and exploring new perspectives and potential\
    \ collaborations\u2014both in terms of research papers and project proposals."
  title: European Mobility Symposium
  venue: Officine Garibaldi, Aula Master
site:
  author: European Mobility Symposium Organizers
  description: Sharing insights from recent works on human mobility
  title: European Mobility Symposium
  url: https://username.github.io/european-mobility-symposium
